spring:
  profiles:
    active: mysql
  main:
    allow-bean-definition-overriding: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: familysabthinga@gmail.com
    password: hhxornpaluxlwncd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

vms:
  jwt:
    secret: 9a4f2c8d3b7a1e5f8g9h0i1j2k3l4m5n6o7p8q9r0s1t2u3v4w5x6y7z8a9b0c1d
    expiration: 3600000 # 1 hour

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:file:./vmsdb;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/vehicle_main?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "rootroot"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

# Common config
server:
  error:
    include-message: always
    include-binding-errors: always
